#version: '3'

#services:
#  db:
#    image: postgres:alpine
#    container_name: db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: mysecretpassword
#      POSTGRES_DB: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      webnet:
#        ipv4_address: 192.168.32.2

#  auth:
#    build: ./auth
#    container_name: auth_service
#    ports:
#      - "8001:8001"
#    environment:
#      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/postgres
#    depends_on:
#      - db
#    networks:
#      webnet:
#        ipv4_address: 192.168.32.3
#  chat:
#    build: ./chat
#    container_name: chat_service
#    ports:
#      - "8000:8000"
#    environment:
#      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5433/postgres
#    depends_on:
#      - db
#      - redis
#    networks:
#      webnet:
#        ipv4_address: 192.168.32.4

#  front:
#    build: ./front
#    container_name: frontend_service
#    ports:
#      - "3000:80"
#    depends_on:
#      - auth
#      - chat
#    networks:
#      webnet:
#        ipv4_address: 192.168.32.5

#  nginx:
#    build: ./nginx
#    container_name: nginx_server
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /etc/letsencrypt/live/43server.com/fullchain.pem:/etc/letsencrypt/live/43server.com/fullchain.pem:ro
#      - /etc/letsencrypt/live/43server.com/privkey.pem:/etc/letsencrypt/live/43server.com/privkey.pem:ro
#      - ./nginx/default.conf:/etc/nginx/nginx.conf
#      - letsencrypt:/etc/letsencrypt
#    depends_on:
#      - front
#      - auth
#      - chat
#    networks:
#      webnet:
#        ipv4_address: 192.168.32.6

#  redis:
#    image: redis:alpine
#    container_name: redis_server
#    ports:
#      - "6379:6379"
#    networks:
#      webnet:
#        ipv4_address: 192.168.32.7

#volumes:
#  postgres_data:
#  letsencrypt:

#networks:
#  webnet:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.32.0/24

version: "3"

services:
  auth_db:
    image: postgres:alpine
    container_name: auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: auth_db
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      webnet:
        ipv4_address: 192.168.32.2

  chat_db:
    image: postgres:alpine
    container_name: chat_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: chat_db
    volumes:
      - chat_postgres_data:/var/lib/postgresql/data
    networks:
      webnet:
        ipv4_address: 192.168.32.3

  auth:
    build: ./auth
    container_name: auth_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@auth_db:5432/auth_db
    depends_on:
      - auth_db
    networks:
      webnet:
        ipv4_address: 192.168.32.4

  chat:
    build: ./chat
    container_name: chat_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@chat_db:5432/chat_db
    depends_on:
      - chat_db
      - redis
    networks:
      webnet:
        ipv4_address: 192.168.32.5

  front:
    build: ./front
    container_name: frontend_service
    ports:
      - "3000:80"
    depends_on:
      - auth
      - chat
    networks:
      webnet:
        ipv4_address: 192.168.32.6

  nginx:
    build: ./nginx
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/43server.com/fullchain.pem:/etc/letsencrypt/live/43server.com/fullchain.pem:ro
      - /etc/letsencrypt/live/43server.com/privkey.pem:/etc/letsencrypt/live/43server.com/privkey.pem:ro
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - front
      - auth
      - chat
    networks:
      webnet:
        ipv4_address: 192.168.32.7

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      webnet:
        ipv4_address: 192.168.32.8

volumes:
  auth_postgres_data:
  chat_postgres_data:
  letsencrypt:

networks:
  webnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.32.0/24
